export {default  as Home} from "./Home"
export {default as About} from "./About"
export {default as MyPortfolio} from "./MyPortfolio"
export {default as Comments} from "./Comment"
export {default as Contact} from "./Contact"
export {default as ContactForm} from "./ContactForm"